name: task_manager
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  
  # Packages for our app
  table_calendar: ^3.0.9
  provider: ^6.0.0
  shared_preferences: ^2.0.0
  google_fonts: ^6.0.0
  image_picker: ^1.0.0
  
  # --- This is the new line ---
  uuid: ^4.0.0
  confetti: ^0.7.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true